import "./globals.css";
import { Plus_Jakarta_Sans as PlusJakartaSans } from "next/font/google";

import Provider from "@/components/Provider";

const plusJakartaSans = PlusJakartaSans({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-plus-jakarta-sans",
  weight: ["200", "300", "400", "500", "600", "700", "800"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = ({ children }) => {
  return (
    <html lang="en" className={plusJakartaSans.variable}>
      <Provider>
        <body className="flex items-center justify-center bg-[#E1E2EF]">
          <main className="flex h-fit min-h-[700px] w-full max-w-screen-mobile flex-col rounded-t-[20px] bg-white">
            {children}
          </main>
        </body>
      </Provider>
    </html>
  );
};

export default RootLayout;
